# Generated by Django 4.0.3 on 2022-04-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='sarlavha',
            field=models.CharField(max_length=50),
        ),
    ]
